{{- range .Values.deployments }}
{{- $deploymentName := .name }}
{{- range .addOns }}
{{- if eq .type "deployment" }}
---
{{- include .helper (dict "arguments" .arguments "name" $deploymentName)  }}
{{- end }}
{{- end }}
{{- end }}
