{{/* vim: set filetype=mustache: */}}
{{- define "mammatus.container.probe" -}}
startupProbe:
  httpGet:
    path: {{ .arguments.startUp.path }}
    port: {{ .arguments.startUp.vhost }}
  failureThreshold: 30
  periodSeconds: 1
livenessProbe:
  httpGet:
    path: {{ .arguments.liveness.path }}
    port: {{ .arguments.liveness.vhost }}
  failureThreshold: 3
  periodSeconds: 1
readinessProbe:
  httpGet:
    path: {{ .arguments.readiness.path }}
    port: {{ .arguments.readiness.vhost }}
  failureThreshold: 3
  periodSeconds: 1
{{- end -}}
