{{/* vim: set filetype=mustache: */}}
{{- define "mammatus.container.resources" -}}
resources:
  limits:
    cpu: {{ .arguments.cpu }}
    memory: {{ .arguments.memory }}
  requests:
    cpu: {{ .arguments.cpu }}
    memory: {{ .arguments.memory }}
{{- end -}}

