{{/* vim: set filetype=mustache: */}}
{{- define "mammatus.pod" -}}
containers:
  - name: {{ .name }}
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    command:
      - php
      - /opt/app/vendor/bin/{{ .command | default "mamatus"}}
            {{- range .arguments }}
      - "{{ . | replace "\\" "\\\\" }}"
            {{- end }}
{{- include "mammatus.env" . | nindent 4 }}
    resources:
      limits:
        cpu: {{ $.Values.resources.cpu }}
        memory: {{ $.Values.resources.memmory }}
      requests:
        cpu: {{ $.Values.resources.cpu }}
        memory: {{ $.Values.resources.memmory }}
{{- include "mammatus.volumeMounts" . | nindent 4 }}
{{ include "mammatus.volumes" . }}
{{- end }}

{{- define "mammatus.env" -}}
env:
  - name: RELEASE_TAG
    value: {{ .Values.image.tag }}
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: "metadata.name"
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: "metadata.namespace"
{{- if or .Values.env .Values.secrets }}
envFrom:
{{- end }}
{{- if .Values.secrets }}
{{- range .Values.secrets }}
  - secretRef:
      name: {{ .name }}
    prefix: {{ .prefix }}
{{- end }}
{{- end }}
{{- if .Values.env }}
  - configMapRef:
      name: env
{{- end }}
{{- end -}}

{{- define "mammatus.volumeMounts" -}}
{{ if .Values.volumes }}
volumeMounts:
{{- range $name, $options := .Values.volumes }}
  - name: {{ $name }}
    {{ $options.volumeMountOptions | toYaml }}
{{- end -}}
{{- end -}}
{{- end -}}

{{- define "mammatus.volumes" -}}
{{ if .Values.volumes }}
volumes:
{{- range $name, $options := .Values.volumes }}
  - name: {{ $name }}
    {{- $options.volumeOptions | toYaml | nindent 4 }}
{{- end -}}
{{- end -}}
{{- end -}}

