{{- range .Values.cronjobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/name: {{ include "mammatus.name" $ }}
    app.kubernetes.io/instance: {{ .name }}
spec:
{{- if eq $.Values.release "dev" }}
  schedule: "* * * * *"
{{- else }}
  schedule: "{{ .schedule }}"
{{- end }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          {{- with $.Values.priorityClassName }}
          priorityClassName: "{{ . }}"
          {{- end }}
          restartPolicy: Never
          {{- include "mammatus.pod" (dict "Chart" $.Chart "Values" $.Values "name" .name "arguments" (list .class) "command" "mammatus-cron" "addOns" .addOns) | nindent 10 }}
{{- end }}
