{{- range .Values.mammatus.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/name: {{ include "mammatus.name" $ }}
    app.kubernetes.io/instance: {{ .name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mammatus.name" $ }}
      app.kubernetes.io/instance: {{ .name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mammatus.name" $ }}
        app.kubernetes.io/instance: {{ .name }}
    spec:
      {{- include "mammatus.pod" (dict "Chart" $.Chart "Values" $.Values "name" .name "arguments" .arguments) | nindent 6 }}
{{- end }}
