{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/name: {{ include "mammatus.name" $ }}
    app.kubernetes.io/instance: {{ .name }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "mammatus.name" $ }}
    app.kubernetes.io/instance: {{ .group }}
  ports:
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ .port }}
{{- end }}
