name: "helm-charts/test"

on: pull_request

jobs:
  kubernetes-versions:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: JLLeitschuh/endoflife-matrix-action@releases/v1
        with:
          product: kubernetes
    outputs:
      matrix: ${{ steps.release.outputs.versions }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Install Chart Tester
        uses: helm/chart-testing-action@v2.6.1
      - name: Lint charts
        id: lint
        run: ct lint --all --target-branch ${{ github.event.repository.default_branch }}
  test:
    runs-on: ubuntu-latest
    needs:
      - lint
      - kubernetes-versions
    strategy:
      fail-fast: false
      matrix:
        k8s: ${{ fromJson(needs.kubernetes-versions.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          installLocalPathProvisioner: true # Only build a kind cluster if there are chart changes to test.
          node_image: "kindest/node:v${{ matrix.k8s }}.0"
          config: etc/kind.yaml
      - run: kubectl get nodes
      - name: Install Chart Tester
        uses: helm/chart-testing-action@v2.6.1
      - name: Test charts
        run: ct install --config ct.yaml --target-branch ${{ github.event.repository.default_branch }}
