name: "helm-charts/test"

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Install Chart Tester
        uses: helm/chart-testing-action@v2.7.0
      - name: Lint charts
        id: lint
        run: ct lint --all --target-branch ${{ github.event.repository.default_branch }}

  test:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        k8s:
          - "1.28"
          - "1.29"
          - "1.30"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0
        with:
          installLocalPathProvisioner: true # Only build a kind cluster if there are chart changes to test.
          node_image: "kindest/node:v${{ matrix.k8s }}.0"
          config: etc/kind.yaml
      - run: kubectl get nodes
      - name: Install Chart Tester
        uses: helm/chart-testing-action@v2.7.0
      - name: Test charts
        run: ct install --config ct.yaml --target-branch ${{ github.event.repository.default_branch }}
